# -*- coding: utf-8 -*-
import server.extraServerApi as extraServerApi
import client.extraClientApi as extraClientApi
import common.game as game
server = game.GetServer()
client = game.GetClient()

from modbe.internal.module.ModBE import ModBE

import functools

__all__ = ["_achievement", "_action", "_actorCollidable", "_actorLoot", "_actorMotion", "_actorOwner", "_actorPushable", "_actorRender", "_armorSlot", "_attr", "_auxValue", "_biome", "_block", "_blockEntityData", "_blockGeometry", "_blockInfo", "_blockState", "_blockUseEventWhiteList", "_breath", "_brightness", "_buff", "_bulletAttributes", "_camera", "_carried", "_chatExtension", "_chestBlock", "_chunkSource", "_cloudMusic", "_collisionBox", "_command", "_controlAi", "_customAudio", "_customItem", "_deathCount", "_device", "_dimension", "_effect", "_effectInfo", "_engineEffectBindControl", "_engineType", "_entityComponent", "_entityEvent", "_exp", "_explosion", "_extraData", "_feature", "_fly", "_fog", "_frameAniControl", "_frameAniEntityBind", "_frameAniNativeEntityBoneBind", "_frameAniSkeletonBind", "_frameAniTrans", "_game", "_gravity", "_health", "_httpToServer", "_hurt", "_interact", "_inventory", "_item", "_itembanned", "_itemInfo", "_lobbyGood", "_lv", "_miniMap", "_mobSpawn", "_modAttr", "_model", "_mouseHook", "_moveTo", "_msg", "_name", "_neApi", "_offHand", "_operation", "_particleControl", "_particleEntityBind", "_particleNativeEntityBoneBind", "_particleSkeletonBind", "_particleSystem", "_particleTrans", "_path", "_persistence", "_pet", "_player", "_playeranim", "_playerView", "_playerKillCount", "_portal", "_pos", "_postprocess", "_queryVariable", "_projectile", "_recipe", "_redStone", "_research", "_ride", "_rot", "_scale", "_seasonMod", "_shareables", "_Shop", "_sign", "_simpleMsg", "_skyRender", "_spawn", "_speed", "_storyline", "_systemAudio", "_tag", "_tame", "_team", "_teamId", "_textBoard", "_textNotifyClient", "_time", "_totalKillCount", "_type", "_vDeliverComp", "_virtualWorld", "_weather"]

# partial component
_achievement = None
_action = None
_actorCollidable = None
_actorLoot = None
_actorMotion = None
_actorOwner = None
_actorPushable = None
_actorRender = None
_armorSlot = None
_attr = None
_auxValue = None
_biome = None
_block = None
_blockEntityData = None
_blockGeometry = None
_blockInfo = None
_blockState = None
_blockUseEventWhiteList = None
_breath = None
_brightness = None
_buff = None
_bulletAttributes = None
_camera = None
_carried = None
_chatExtension = None
_chestBlock = None
_chunkSource = None
_cloudMusic = None
_collisionBox = None
_command = None
_controlAi = None
_customAudio = None
_customItem = None
_deathCount = None
_device = None
_dimension = None
_effect = None
_effectInfo = None
_engineEffectBindControl = None
_engineType = None
_entityComponent = None
_entityEvent = None
_exp = None
_explosion = None
_extraData = None
_feature = None
_fly = None
_fog = None
_frameAniControl = None
_frameAniEntityBind = None
_frameAniNativeEntityBoneBind = None
_frameAniSkeletonBind = None
_frameAniTrans = None
_game = None
_gravity = None
_health = None
_httpToServer = None
_hurt = None
_interact = None
_inventory = None
_item = None
_itembanned = None
_itemInfo = None
_lobbyGood = None
_lv = None
_miniMap = None
_mobSpawn = None
_modAttr = None
_model = None
_mouseHook = None
_moveTo = None
_msg = None
_name = None
_neApi = None
_offHand = None
_operation = None
_particleControl = None
_particleEntityBind = None
_particleNativeEntityBoneBind = None
_particleSkeletonBind = None
_particleSystem = None
_particleTrans = None
_path = None
_persistence = None
_pet = None
_player = None
_playeranim = None
_playerView = None
_playerKillCount = None
_portal = None
_pos = None
_postprocess = None
_queryVariable = None
_projectile = None
_recipe = None
_redStone = None
_research = None
_ride = None
_rot = None
_scale = None
_seasonMod = None
_shareables = None
_Shop = None
_sign = None
_simpleMsg = None
_skyRender = None
_spawn = None
_speed = None
_storyline = None
_systemAudio = None
_tag = None
_tame = None
_team = None
_teamId = None
_textBoard = None
_textNotifyClient = None
_time = None
_totalKillCount = None
_type = None
_vDeliverComp = None
_virtualWorld = None
_weather = None

# level specific component
__achievement = None
__action = None
__actorCollidable = None
__actorLoot = None
__actorMotion = None
__actorOwner = None
__actorPushable = None
__actorRender = None
__armorSlot = None
__attr = None
__auxValue = None
__biome = None
__block = None
__blockEntityData = None
__blockGeometry = None
__blockInfo = None
__blockState = None
__blockUseEventWhiteList = None
__breath = None
__brightness = None
__buff = None
__bulletAttributes = None
__camera = None
__carried = None
__chatExtension = None
__chestBlock = None
__chunkSource = None
__cloudMusic = None
__collisionBox = None
__command = None
__controlAi = None
__customAudio = None
__customItem = None
__deathCount = None
__device = None
__dimension = None
__effect = None
__effectInfo = None
__engineEffectBindControl = None
__engineType = None
__entityComponent = None
__entityEvent = None
__exp = None
__explosion = None
__extraData = None
__feature = None
__fly = None
__fog = None
__frameAniControl = None
__frameAniEntityBind = None
__frameAniNativeEntityBoneBind = None
__frameAniSkeletonBind = None
__frameAniTrans = None
__game = None
__gravity = None
__health = None
__httpToServer = None
__hurt = None
__interact = None
__inventory = None
__item = None
__itembanned = None
__itemInfo = None
__lobbyGood = None
__lv = None
__miniMap = None
__mobSpawn = None
__modAttr = None
__model = None
__mouseHook = None
__moveTo = None
__msg = None
__name = None
__neApi = None
__offHand = None
__operation = None
__particleControl = None
__particleEntityBind = None
__particleNativeEntityBoneBind = None
__particleSkeletonBind = None
__particleSystem = None
__particleTrans = None
__path = None
__persistence = None
__pet = None
__player = None
__playeranim = None
__playerView = None
__playerKillCount = None
__portal = None
__pos = None
__postprocess = None
__queryVariable = None
__projectile = None
__recipe = None
__redStone = None
__research = None
__ride = None
__rot = None
__scale = None
__seasonMod = None
__shareables = None
__Shop = None
__sign = None
__simpleMsg = None
__skyRender = None
__spawn = None
__speed = None
__storyline = None
__systemAudio = None
__tag = None
__tame = None
__team = None
__teamId = None
__textBoard = None
__textNotifyClient = None
__time = None
__totalKillCount = None
__type = None
__vDeliverComp = None
__virtualWorld = None
__weather = None

if ModBE.isServer():
    _factory = extraServerApi.GetEngineCompFactory()
    _achievement = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "achievement"})
    _action = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "action"})
    _actorCollidable = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "actorCollidable"})
    _actorLoot = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "actorLoot"})
    _actorMotion = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "actorMotion"})
    _actorOwner = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "actorOwner"})
    _actorPushable = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "actorPushable"})
    _armorSlot = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "armorSlot"})
    _attr = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "attr"})
    _auxValue = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "auxValue"})
    _biome = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "biome"})
    _block = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "block"})
    _blockEntityData = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "blockEntityData"})
    _blockInfo = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "blockInfo"})
    _blockState = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "blockState"})
    _blockUseEventWhiteList = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "blockUseEventWhiteList"})
    _breath = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "breath"})
    _buff = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "buff"})
    _bulletAttributes = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "bulletAttributes"})
    _carried = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "carried"})
    _chatExtension = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "chatExtension"})
    _chestBlock = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "chestBlock"})
    _chunkSource = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "chunkSource"})
    _collisionBox = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "collisionBox"})
    _command = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "command"})
    _controlAi = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "controlAi"})
    _customItem = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "customItem"})
    _deathCount = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "deathCount"})
    _dimension = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "dimension"})
    _effect = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "effect"})
    _engineType = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "engineType"})
    _entityComponent = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "entityComponent"})
    _entityEvent = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "entityEvent"})
    _exp = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "exp"})
    _explosion = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "explosion"})
    _extraData = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "extraData"})
    _feature = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "feature"})
    _fly = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "fly"})
    _game = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "game"})
    _gravity = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "gravity"})
    _health = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "health"})
    _httpToServer = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "httpToServer"})
    _hurt = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "hurt"})
    _interact = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "interact"})
    _inventory = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "inventory"})
    _item = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "item"})
    _itembanned = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "itembanned"})
    _itemInfo = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "itemInfo"})
    _lobbyGood = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "lobbyGood"})
    _lv = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "lv"})
    _mobSpawn = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "mobSpawn"})
    _modAttr = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "modAttr"})
    _model = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "model"})
    _moveTo = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "moveTo"})
    _msg = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "msg"})
    _name = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "name"})
    _neApi = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "neApi"})
    _offHand = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "offHand"})
    _persistence = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "persistence"})
    _pet = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "pet"})
    _player = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "player"})
    _playerKillCount = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "playerKillCount"})
    _portal = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "portal"})
    _pos = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "pos"})
    _projectile = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "projectile"})
    _recipe = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "recipe"})
    _redStone = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "redStone"})
    _ride = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "ride"})
    _rot = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "rot"})
    _scale = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "scale"})
    _seasonMod = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "seasonMod"})
    _shareables = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "shareables"})
    _sign = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "sign"})
    _simpleMsg = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "simpleMsg"})
    _spawn = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "spawn"})
    _speed = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "speed"})
    _storyline = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "storyline"})
    _systemAudio = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "systemAudio"})
    _tag = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "tag"})
    _tame = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "tame"})
    _team = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "team"})
    _teamId = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "teamId"})
    _time = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "time"})
    _totalKillCount = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "totalKillCount"})
    _type = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "type"})
    _vDeliverComp = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "vDeliverComp"})
    _weather = functools.partial(server.CreateComponent, **{"nameSpace": "Minecraft", "name": "weather"})

    __achievement = _achievement(extraServerApi.GetLevelId())
    __action = _action(extraServerApi.GetLevelId())
    __actorCollidable = _actorCollidable(extraServerApi.GetLevelId())
    __actorLoot = _actorLoot(extraServerApi.GetLevelId())
    __actorMotion = _actorMotion(extraServerApi.GetLevelId())
    __actorOwner = _actorOwner(extraServerApi.GetLevelId())
    __actorPushable = _actorPushable(extraServerApi.GetLevelId())
    __armorSlot = _armorSlot(extraServerApi.GetLevelId())
    __attr = _attr(extraServerApi.GetLevelId())
    __auxValue = _auxValue(extraServerApi.GetLevelId())
    __biome = _biome(extraServerApi.GetLevelId())
    __block = _block(extraServerApi.GetLevelId())
    __blockEntityData = _blockEntityData(extraServerApi.GetLevelId())
    __blockInfo = _blockInfo(extraServerApi.GetLevelId())
    __blockState = _blockState(extraServerApi.GetLevelId())
    __blockUseEventWhiteList = _blockUseEventWhiteList(extraServerApi.GetLevelId())
    __breath = _breath(extraServerApi.GetLevelId())
    __buff = _buff(extraServerApi.GetLevelId())
    __bulletAttributes = _bulletAttributes(extraServerApi.GetLevelId())
    __carried = _carried(extraServerApi.GetLevelId())
    __chatExtension = _chatExtension(extraServerApi.GetLevelId())
    __chestBlock = _chestBlock(extraServerApi.GetLevelId())
    __chunkSource = _chunkSource(extraServerApi.GetLevelId())
    __collisionBox = _collisionBox(extraServerApi.GetLevelId())
    __command = _command(extraServerApi.GetLevelId())
    __controlAi = _controlAi(extraServerApi.GetLevelId())
    __customItem = _customItem(extraServerApi.GetLevelId())
    __deathCount = _deathCount(extraServerApi.GetLevelId())
    __dimension = _dimension(extraServerApi.GetLevelId())
    __effect = _effect(extraServerApi.GetLevelId())
    __engineType = _engineType(extraServerApi.GetLevelId())
    __entityComponent = _entityComponent(extraServerApi.GetLevelId())
    __entityEvent = _entityEvent(extraServerApi.GetLevelId())
    __exp = _exp(extraServerApi.GetLevelId())
    __explosion = _explosion(extraServerApi.GetLevelId())
    __extraData = _extraData(extraServerApi.GetLevelId())
    __feature = _feature(extraServerApi.GetLevelId())
    __fly = _fly(extraServerApi.GetLevelId())
    __game = _game(extraServerApi.GetLevelId())
    __gravity = _gravity(extraServerApi.GetLevelId())
    __health = _health(extraServerApi.GetLevelId())
    __httpToServer = _httpToServer(extraServerApi.GetLevelId())
    __hurt = _hurt(extraServerApi.GetLevelId())
    __interact = _interact(extraServerApi.GetLevelId())
    __inventory = _inventory(extraServerApi.GetLevelId())
    __item = _item(extraServerApi.GetLevelId())
    __itembanned = _itembanned(extraServerApi.GetLevelId())
    __itemInfo = _itemInfo(extraServerApi.GetLevelId())
    __lobbyGood = _lobbyGood(extraServerApi.GetLevelId())
    __lv = _lv(extraServerApi.GetLevelId())
    __mobSpawn = _mobSpawn(extraServerApi.GetLevelId())
    __modAttr = _modAttr(extraServerApi.GetLevelId())
    __model = _model(extraServerApi.GetLevelId())
    __moveTo = _moveTo(extraServerApi.GetLevelId())
    __msg = _msg(extraServerApi.GetLevelId())
    __name = _name(extraServerApi.GetLevelId())
    __neApi = _neApi(extraServerApi.GetLevelId())
    __offHand = _offHand(extraServerApi.GetLevelId())
    __persistence = _persistence(extraServerApi.GetLevelId())
    __pet = _pet(extraServerApi.GetLevelId())
    __player = _player(extraServerApi.GetLevelId())
    __playerKillCount = _playerKillCount(extraServerApi.GetLevelId())
    __portal = _portal(extraServerApi.GetLevelId())
    __pos = _pos(extraServerApi.GetLevelId())
    __projectile = _projectile(extraServerApi.GetLevelId())
    __recipe = _recipe(extraServerApi.GetLevelId())
    __redStone = _redStone(extraServerApi.GetLevelId())
    __ride = _ride(extraServerApi.GetLevelId())
    __rot = _rot(extraServerApi.GetLevelId())
    __scale = _scale(extraServerApi.GetLevelId())
    __seasonMod = _seasonMod(extraServerApi.GetLevelId())
    __shareables = _shareables(extraServerApi.GetLevelId())
    __sign = _sign(extraServerApi.GetLevelId())
    __simpleMsg = _simpleMsg(extraServerApi.GetLevelId())
    __spawn = _spawn(extraServerApi.GetLevelId())
    __speed = _speed(extraServerApi.GetLevelId())
    __storyline = _storyline(extraServerApi.GetLevelId())
    __systemAudio = _systemAudio(extraServerApi.GetLevelId())
    __tag = _tag(extraServerApi.GetLevelId())
    __tame = _tame(extraServerApi.GetLevelId())
    __team = _team(extraServerApi.GetLevelId())
    __teamId = _teamId(extraServerApi.GetLevelId())
    __time = _time(extraServerApi.GetLevelId())
    __totalKillCount = _totalKillCount(extraServerApi.GetLevelId())
    __type = _type(extraServerApi.GetLevelId())
    __vDeliverComp = _vDeliverComp(extraServerApi.GetLevelId())
    __weather = _weather(extraServerApi.GetLevelId())
if ModBE.isClient():
    _factory = extraClientApi.GetEngineCompFactory()
    _action = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "action"})
    _actorCollidable = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "actorCollidable"})
    _actorMotion = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "actorMotion"})
    _actorRender = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "actorRender"})
    _attr = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "attr"})
    _auxValue = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "auxValue"})
    _biome = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "biome"})
    _block = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "block"})
    _blockGeometry = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "blockGeometry"})
    _blockInfo = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "blockInfo"})
    _blockUseEventWhiteList = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "blockUseEventWhiteList"})
    _brightness = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "brightness"})
    _bulletAttributes = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "bulletAttributes"})
    _camera = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "camera"})
    _carried = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "carried"})
    _chunkSource = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "chunkSource"})
    _cloudMusic = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "cloudMusic"})
    _collisionBox = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "collisionBox"})
    _config = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "config"})
    _customAudio = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "customAudio"})
    _customItem = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "customItem"})
    _device = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "device"})
    _effect = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "effect"})
    _effectInfo = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "effectInfo"})
    _engineEffectBindControl = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "engineEffectBindControl"})
    _engineType = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "engineType"})
    _fog = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "fog"})
    _frameAniControl = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "frameAniControl"})
    _frameAniEntityBind = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "frameAniEntityBind"})
    _frameAniNativeEntityBoneBind = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "frameAniNativeEntityBoneBind"})
    _frameAniSkeletonBind = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "frameAniSkeletonBind"})
    _frameAniTrans = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "frameAniTrans"})
    _game = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "game"})
    _health = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "health"})
    _inventory = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "inventory"})
    _item = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "item"})
    _miniMap = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "miniMap"})
    _modAttr = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "modAttr"})
    _model = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "model"})
    _mouseHook = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "mouseHook"})
    _name = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "name"})
    _neApi = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "neApi"})
    _offHand = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "offHand"})
    _operation = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "operation"})
    _particleControl = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "particleControl"})
    _particleEntityBind = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "particleEntityBind"})
    _particleNativeEntityBoneBind = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "particleNativeEntityBoneBind"})
    _particleSkeletonBind = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "particleSkeletonBind"})
    _particleSystem = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "particleSystem"})
    _particleTrans = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "particleTrans"})
    _path = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "path"})
    _player = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "player"})
    _playeranim = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "playeranim"})
    _playerView = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "playerView"})
    _pos = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "pos"})
    _postprocess = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "postprocess"})
    _queryVariable = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "queryVariable"})
    _recipe = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "recipe"})
    _research = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "research"})
    _ride = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "ride"})
    _rot = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "rot"})
    _seasonMod = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "seasonMod"})
    _Shop = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "Shop"})
    _skyRender = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "skyRender"})
    _systemAudio = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "systemAudio"})
    _tame = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "tame"})
    _textBoard = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "textBoard"})
    _textNotifyClient = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "textNotifyClient"})
    _time = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "time"})
    _type = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "type"})
    _virtualWorld = functools.partial(client.CreateComponent, **{"nameSpace": "Minecraft", "name": "virtualWorld"})

    __action = _action(extraClientApi.GetLevelId())
    __actorCollidable = _actorCollidable(extraClientApi.GetLevelId())
    __actorMotion = _actorMotion(extraClientApi.GetLevelId())
    __actorRender = _actorRender(extraClientApi.GetLevelId())
    __attr = _attr(extraClientApi.GetLevelId())
    __auxValue = _auxValue(extraClientApi.GetLevelId())
    __biome = _biome(extraClientApi.GetLevelId())
    __block = _block(extraClientApi.GetLevelId())
    __blockGeometry = _blockGeometry(extraClientApi.GetLevelId())
    __blockInfo = _blockInfo(extraClientApi.GetLevelId())
    __blockUseEventWhiteList = _blockUseEventWhiteList(extraClientApi.GetLevelId())
    __brightness = _brightness(extraClientApi.GetLevelId())
    __bulletAttributes = _bulletAttributes(extraClientApi.GetLevelId())
    __camera = _camera(extraClientApi.GetLevelId())
    __carried = _carried(extraClientApi.GetLevelId())
    __chunkSource = _chunkSource(extraClientApi.GetLevelId())
    __cloudMusic = _cloudMusic(extraClientApi.GetLevelId())
    __collisionBox = _collisionBox(extraClientApi.GetLevelId())
    __config = _config(extraClientApi.GetLevelId())
    __customAudio = _customAudio(extraClientApi.GetLevelId())
    __customItem = _customItem(extraClientApi.GetLevelId())
    __device = _device(extraClientApi.GetLevelId())
    __effect = _effect(extraClientApi.GetLevelId())
    __effectInfo = _effectInfo(extraClientApi.GetLevelId())
    __engineEffectBindControl = _engineEffectBindControl(extraClientApi.GetLevelId())
    __engineType = _engineType(extraClientApi.GetLevelId())
    __fog = _fog(extraClientApi.GetLevelId())
    __frameAniControl = _frameAniControl(extraClientApi.GetLevelId())
    __frameAniEntityBind = _frameAniEntityBind(extraClientApi.GetLevelId())
    __frameAniNativeEntityBoneBind = _frameAniNativeEntityBoneBind(extraClientApi.GetLevelId())
    __frameAniSkeletonBind = _frameAniSkeletonBind(extraClientApi.GetLevelId())
    __frameAniTrans = _frameAniTrans(extraClientApi.GetLevelId())
    __game = _game(extraClientApi.GetLevelId())
    __health = _health(extraClientApi.GetLevelId())
    __inventory = _inventory(extraClientApi.GetLevelId())
    __item = _item(extraClientApi.GetLevelId())
    __miniMap = _miniMap(extraClientApi.GetLevelId())
    __modAttr = _modAttr(extraClientApi.GetLevelId())
    __model = _model(extraClientApi.GetLevelId())
    __mouseHook = _mouseHook(extraClientApi.GetLevelId())
    __name = _name(extraClientApi.GetLevelId())
    __neApi = _neApi(extraClientApi.GetLevelId())
    __offHand = _offHand(extraClientApi.GetLevelId())
    __operation = _operation(extraClientApi.GetLevelId())
    __particleControl = _particleControl(extraClientApi.GetLevelId())
    __particleEntityBind = _particleEntityBind(extraClientApi.GetLevelId())
    __particleNativeEntityBoneBind = _particleNativeEntityBoneBind(extraClientApi.GetLevelId())
    __particleSkeletonBind = _particleSkeletonBind(extraClientApi.GetLevelId())
    __particleSystem = _particleSystem(extraClientApi.GetLevelId())
    __particleTrans = _particleTrans(extraClientApi.GetLevelId())
    __path = _path(extraClientApi.GetLevelId())
    __player = _player(extraClientApi.GetLevelId())
    __playeranim = _playeranim(extraClientApi.GetLevelId())
    __playerView = _playerView(extraClientApi.GetLevelId())
    __pos = _pos(extraClientApi.GetLevelId())
    __postprocess = _postprocess(extraClientApi.GetLevelId())
    __queryVariable = _queryVariable(extraClientApi.GetLevelId())
    __recipe = _recipe(extraClientApi.GetLevelId())
    __research = _research(extraClientApi.GetLevelId())
    __ride = _ride(extraClientApi.GetLevelId())
    __rot = _rot(extraClientApi.GetLevelId())
    __seasonMod = _seasonMod(extraClientApi.GetLevelId())
    __Shop = _Shop(extraClientApi.GetLevelId())
    __skyRender = _skyRender(extraClientApi.GetLevelId())
    __systemAudio = _systemAudio(extraClientApi.GetLevelId())
    __tame = _tame(extraClientApi.GetLevelId())
    __textBoard = _textBoard(extraClientApi.GetLevelId())
    __textNotifyClient = _textNotifyClient(extraClientApi.GetLevelId())
    __time = _time(extraClientApi.GetLevelId())
    __type = _type(extraClientApi.GetLevelId())
    __virtualWorld = _virtualWorld(extraClientApi.GetLevelId())
